// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9iv4z-jmCI3akucVcY5e0dqHYhYNnILw',
    appId: '1:331317349047:web:8034b266a4410245525b32',
    messagingSenderId: '331317349047',
    projectId: 'flutter-varios-74ae7',
    authDomain: 'flutter-varios-74ae7.firebaseapp.com',
    databaseURL: 'https://flutter-varios-74ae7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-74ae7.appspot.com',
    measurementId: 'G-ZYQ2JS136X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKZFvYLwJ7WMkX0nEKnuZvElrrov1yaGo',
    appId: '1:331317349047:android:6cae9c53ab6f5368525b32',
    messagingSenderId: '331317349047',
    projectId: 'flutter-varios-74ae7',
    databaseURL: 'https://flutter-varios-74ae7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-74ae7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDZL2-V8cxI1wey93BH-Qi6_1HkpsAkMw',
    appId: '1:331317349047:ios:bb7f38d15bda5d16525b32',
    messagingSenderId: '331317349047',
    projectId: 'flutter-varios-74ae7',
    databaseURL: 'https://flutter-varios-74ae7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-varios-74ae7.appspot.com',
    androidClientId: '331317349047-5fpbu28of5f5cr95qv9c5lsiqqc4n8mr.apps.googleusercontent.com',
    iosClientId: '331317349047-m2fmmtssf1ksrrl41i8ehkp29t81ngri.apps.googleusercontent.com',
    iosBundleId: 'com.adelgado.comicvine',
  );
}
